version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - SCRAPYRT_HOST=scrapyrt
    depends_on:
      - redis
      - scrapyrt
    volumes:
      - .:/app
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
  scrapyrt:
    image: scrapinghub/scrapyrt
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./scrapyrt:/scrapyrt/project
